# One-Hot Encoding

## What is One-Hot Encoding?

One-Hot Encoding is a text-to-vector technique used in NLP to convert words into numerical vectors. Since machine learning models cannot directly understand text, each unique word is represented using a vector containing `0` and `1`. Each word gets a separate position in the vector, and the position corresponding to that word is represented by `1`, while all other positions are represented by `0`.

For example, if our vocabulary contains `["I", "love", "NLP"]`, the word `I` can be represented as `[1, 0, 0]`, `love` as `[0, 1, 0]`, and `NLP` as `[0, 0, 1]`.

## One-Hot Encoding Implementation

In this implementation, we will create a vocabulary from a set of sentences and represent each word using a one-hot encoded vector. I will use `OneHotEncoder` from `scikit-learn` to perform the encoding.

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import OneHotEncoder

In [3]:
words = np.array([
    ["I"],
    ["love"],
    ["NLP"],
    ["I"],
    ["love"]
])

In [5]:
encoder = OneHotEncoder(sparse_output=False) 
#Create a One-Hot Encoder and give me the result as a normal array.

In [6]:
#Learn the unique words + convert the words into vectors.
encoded_words = encoder.fit_transform(words)

In [7]:
print(encoded_words)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


## Advantages of One-Hot Encoding

- **Simple and easy to understand:** One-hot encoding is straightforward and easy to implement.

- **No numerical relationship between words:** Each word gets a separate vector, so the model does not assume that one word is greater or smaller than another.

- **Easy to implement:** It can be implemented easily using libraries such as Scikit-learn.

- **Useful for small vocabularies:** It works well when the number of unique words is relatively small.

## Disadvantages of One-Hot Encoding

- **High dimensionality:** If the vocabulary contains thousands of words, each word will require a vector with thousands of positions.

- **Sparse vectors:** Most values in the vector are `0`, so a large amount of space may be wasted.

- **Does not capture meaning:** One-hot encoding treats every word as completely independent and does not understand relationships between words.

- **Not suitable for large vocabularies:** As the number of unique words increases, the size of the vectors also increases.

- **No semantic information:** Similar words such as `king` and `queen` do not have similar vectors because each word has its own independent position.